config/routes.rb
Rails.application.routes.draw do
  resources :emergencies
  resources :responders
  resources :fire
  resources :police
  resources :medical

  namespace :api, defaults: {format: 'json'} do
	  resources :emergencies
	  resources :responders
	  resources :fire
	  resources :police
	  resources :medical
  end

end

app/models/emergency.rb
class Emergency < ActiveRecord::Base
end

app/models/fire.rb
class Fire < Responder
  
  def set_type
    self.type = 'Fire'
  end

end

app/models/medical.rb
class Medical < Responder
	
  def set_type
    self.type = 'Medical'
  end

end

app/models/police.rb
class Police < Responder
  
  def set_type
    self.type = 'Police'
  end

end

app/models/responder.rb
class Responder < ActiveRecord::Base
 
  TYPES = %w(Fire Police Medical)
  before_save :set_type
  validates :type, presence: true, :inclusion => { :in => TYPES }
  validates :capacity, presence: true, length: { in: 1..5 }
  validates :name, presence: true, uniqueness: true

  def set_type
    raiser "You must override this method in each model inheriting from Responder!"
  end

end

app/controllers/api/responder_controller.rb
class Api::ResponderController < ApplicationController
  
  responde_to :json

  def create
    @responder = Responder.new(responder_params)
    respond_to do |format|
      if @responder.save
        format.json { render :show, status: :created, location: @responder }
      else
        format.json { render json: @responder.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private

    def responder_params
      params.require(:responder).permit(:type, :name, :capacity)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/emergencies_controller.rb
class EmergenciesController < ApplicationController
  before_action :set_emergency, only: [:show, :edit, :update, :destroy]

  # GET /emergencies
  # GET /emergencies.json
  def index
    @emergencies = Emergency.all
  end

  # GET /emergencies/1
  # GET /emergencies/1.json
  def show
  end

  # GET /emergencies/new
  def new
    @emergency = Emergency.new
  end

  # GET /emergencies/1/edit
  def edit
  end

  # POST /emergencies
  # POST /emergencies.json
  def create
    @emergency = Emergency.new(emergency_params)

    respond_to do |format|
      if @emergency.save
        format.html { redirect_to @emergency, notice: 'Emergency was successfully created.' }
        format.json { render :show, status: :created, location: @emergency }
      else
        format.html { render :new }
        format.json { render json: @emergency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /emergencies/1
  # PATCH/PUT /emergencies/1.json
  def update
    respond_to do |format|
      if @emergency.update(emergency_params)
        format.html { redirect_to @emergency, notice: 'Emergency was successfully updated.' }
        format.json { render :show, status: :ok, location: @emergency }
      else
        format.html { render :edit }
        format.json { render json: @emergency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /emergencies/1
  # DELETE /emergencies/1.json
  def destroy
    @emergency.destroy
    respond_to do |format|
      format.html { redirect_to emergencies_url, notice: 'Emergency was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_emergency
      @emergency = Emergency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def emergency_params
      params.require(:emergency).permit(:code, :fire_severity, :police_severity, :medical_severity)
    end
end

app/controllers/responders_controller.rb
class RespondersController < ApplicationController
  before_action :set_responder, only: [:show, :edit, :update, :destroy]

  # GET /responders
  # GET /responders.json
  def index
    @responders = Responder.all
  end

  # GET /responders/1
  # GET /responders/1.json
  def show
  end

  # GET /responders/new
  def new
    @responder = Responder.new
  end

  # GET /responders/1/edit
  def edit
  end

  # POST /responders
  # POST /responders.json
  def create
    @responder = Responder.new(responder_params)

    respond_to do |format|
      if @responder.save
        format.html { redirect_to @responder, notice: 'Responder was successfully created.' }
        format.json { render :show, status: :created, location: @responder }
      else
        format.html { render :new }
        format.json { render json: @responder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /responders/1
  # PATCH/PUT /responders/1.json
  def update
    respond_to do |format|
      if @responder.update(responder_params)
        format.html { redirect_to @responder, notice: 'Responder was successfully updated.' }
        format.json { render :show, status: :ok, location: @responder }
      else
        format.html { render :edit }
        format.json { render json: @responder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /responders/1
  # DELETE /responders/1.json
  def destroy
    @responder.destroy
    respond_to do |format|
      format.html { redirect_to responders_url, notice: 'Responder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_responder
      @responder = Responder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def responder_params
      params.require(:responder).permit(:type, :name, :capacity)
    end
end

app/helpers/api/responder_helper.rb
module Api::ResponderHelper
end

app/helpers/emergencies_helper.rb
module EmergenciesHelper
end

app/helpers/responders_helper.rb
module RespondersHelper
end

app/views/emergencies/_form.html.erb
<%= form_for(@emergency) do |f| %>
  <% if @emergency.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@emergency.errors.count, "error") %> prohibited this emergency from being saved:</h2>

      <ul>
      <% @emergency.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :fire_severity %><br>
    <%= f.number_field :fire_severity %>
  </div>
  <div class="field">
    <%= f.label :police_severity %><br>
    <%= f.number_field :police_severity %>
  </div>
  <div class="field">
    <%= f.label :medical_severity %><br>
    <%= f.number_field :medical_severity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/emergencies/edit.html.erb
<h1>Editing Emergency</h1>

<%= render 'form' %>

<%= link_to 'Show', @emergency %> |
<%= link_to 'Back', emergencies_path %>

app/views/emergencies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Emergencies</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Fire severity</th>
      <th>Police severity</th>
      <th>Medical severity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @emergencies.each do |emergency| %>
      <tr>
        <td><%= emergency.code %></td>
        <td><%= emergency.fire_severity %></td>
        <td><%= emergency.police_severity %></td>
        <td><%= emergency.medical_severity %></td>
        <td><%= link_to 'Show', emergency %></td>
        <td><%= link_to 'Edit', edit_emergency_path(emergency) %></td>
        <td><%= link_to 'Destroy', emergency, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Emergency', new_emergency_path %>

app/views/emergencies/new.html.erb
<h1>New Emergency</h1>

<%= render 'form' %>

<%= link_to 'Back', emergencies_path %>

app/views/emergencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @emergency.code %>
</p>

<p>
  <strong>Fire severity:</strong>
  <%= @emergency.fire_severity %>
</p>

<p>
  <strong>Police severity:</strong>
  <%= @emergency.police_severity %>
</p>

<p>
  <strong>Medical severity:</strong>
  <%= @emergency.medical_severity %>
</p>

<%= link_to 'Edit', edit_emergency_path(@emergency) %> |
<%= link_to 'Back', emergencies_path %>

app/views/responders/_form.html.erb
<%= form_for(@responder) do |f| %>
  <% if @responder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@responder.errors.count, "error") %> prohibited this responder from being saved:</h2>

      <ul>
      <% @responder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/responders/edit.html.erb
<h1>Editing Responder</h1>

<%= render 'form' %>

<%= link_to 'Show', @responder %> |
<%= link_to 'Back', responders_path %>

app/views/responders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Responders</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Name</th>
      <th>Capacity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @responders.each do |responder| %>
      <tr>
        <td><%= responder.type %></td>
        <td><%= responder.name %></td>
        <td><%= responder.capacity %></td>
        <td><%= link_to 'Show', responder %></td>
        <td><%= link_to 'Edit', edit_responder_path(responder) %></td>
        <td><%= link_to 'Destroy', responder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Responder', new_responder_path %>

app/views/responders/new.html.erb
<h1>New Responder</h1>

<%= render 'form' %>

<%= link_to 'Back', responders_path %>

app/views/responders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @responder.type %>
</p>

<p>
  <strong>Name:</strong>
  <%= @responder.name %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @responder.capacity %>
</p>

<%= link_to 'Edit', edit_responder_path(@responder) %> |
<%= link_to 'Back', responders_path %>